### PR TITLE
link to reccuring event fixed and file saved

### LINKED ISSUE #974: Editing a recurring event removes it's recurring link
The link between recurring events is removed when you edit a recurring event. Something is updating the recurring id improperly

### PR DESCRIPTION
**Pull request by doucoureb**

### CODE REVIEW

**Review by BrianRamsay — APPROVED** [review]

**Comment by BrianRamsay** [comment]
Link your issue to the PR so it will be closed automatically when the PR is merged

**Comment by michelmonc** [comment]
[Editing a recurring event removes it's recurring link #974](https://trello.com/c/JU13O0CK/643-editing-a-recurring-event-removes-its-recurring-link-974)

**Comment by doucoureb** [comment]
Resolves issue #1009

**Comment by michelmonc** [comment]
Resolve #1009

**Comment by michelmonc** [comment]
Resolve #974

**Pull request merged**
