### PR TITLE
Added my name to the list of contributors

### PR DESCRIPTION
**Pull request by Kafui123**
Added my name to the list of contributors

### CODE REVIEW

**Review by BrianRamsay — CHANGES_REQUESTED** [review]
Make sure the title of the PR is meaningful. Also, resolve any merge conflicts.

**Comment by Kafui123** [comment]
> Make sure the title of the PR is meaningful. Also, resolve any merge conflicts.



> Make sure the title of the PR is meaningful. Also, resolve any merge conflict
the changes have been made thank you

**Review by BrianRamsay — DISMISSED** [review]

**Comment by BrianRamsay** [comment]
More merge conflicts!

**Review by Karina-Agliullova — APPROVED** [review]
Looks good!

**Pull request merged**
