### PR TITLE
Event default location

### LINKED ISSUE #1003: Fix default location of events when creating an event
Currently, if you go to create an event that has never had a default location set through the Program Management section, the location input is "None". We should change this so that is in an empty input box in this case.

### PR DESCRIPTION
**Pull request by doucoureb**

### CODE REVIEW

**Comment by doucoureb** [comment]
[Fix default location of events when creating an event #1003](https://trello.com/c/dBSKqJ2r/667-fix-default-location-of-events-when-creating-an-event-1003)

**Comment by doucoureb** [comment]
[Fix default location of events when creating an event #1003](https://trello.com/c/dBSKqJ2r/667-fix-default-location-of-events-when-creating-an-event-1003)

**Comment by michelmonc** [comment]
Resolves issue #1003

**Comment by BrianRamsay** [comment]
Resolve #1003

**Review by BrianRamsay — APPROVED** [review]

**Pull request merged**
