### PR TITLE
Fixed the toggle issue for viewing past events

### PR DESCRIPTION
**Pull request by Karina-Agliullova**
Task: For the past events the view past event toggle needs to be disabled and checked, for both present and future terms, the toggle needs to be unchecked and enabled.

Fixes: We checked if selectedTerm is future or current and if it is then we enabled the toggle but unchecked; if selectedTerm is past then we disabled the toggle but checked, meaning that the past events should be displayed.

Test: To test this, you select the past term in the Events Lists then the toggle should be checked and disabled. If you select the current term or future then the toggle should be enabled but unchecked.

Resolved Issue #1047

### CODE REVIEW

**Comment by doucoureb** [comment]
pr-review
Is also the button supposed to be checked and disabled even when there are no past events but it is a past term?

**Comment by andersoncedu** [comment]
> pr-review Is also the button supposed to be checked and disabled even when there are no past events but it is a past term?


Has this been addressed?

**Comment by Karina-Agliullova** [comment]
> pr-review Is also the button supposed to be checked and disabled even when there are no past events but it is a past term?

- I checked it again. It works correctly because Summer 2021 is set to the current term by default, which is why it shows the behavior of the current term. Fall 2021 is the future term because it goes after Summer 2021, so the behavior would be the same as the current term. So the toggle should be enabled but unchecked. For any other term before Summer 2021, the behavior would be for past terms, which is checked and disabled toggle.

**Comment by azabeli** [comment]
> > pr-review Is also the button supposed to be checked and disabled even when there are no past events but it is a past term?
> 
> Has this been addressed?

Yes, you can refer to Karina's reply to the comment.

**Review by AndersonStettner — APPROVED** [review]

**Pull request merged**
