### PR TITLE
Differentiate prerequisite and event issue15

### PR DESCRIPTION
**Pull request by sreynit02**
**Problem:** 
Need distinction between what is a prerequisite for a program and an event of a program
This PR fixes issue #15 

**Solution:** 
Added programId to event:
In the programevent model there is a column for programId add that column inside of the event model. This way it is clear what event belongs to which program.

Made Table called preqForProgram: 
There was no way to tell if an event was required for a program. The preqForProgram contains two fields programId and eventId. The programevent model was renamed preqForProgram after transferring the programId column. 

Created a program called training:
The training program contains many events and some of those events are prereqs for multiple other programs. We created  Training program (in test data), added multiple events to it, and assigned those events as prereqs for other programs.

We also refactored the code in /app/logic/events.py and added preqForProgram model migrate_db.sh .

**Test:** 
Run ./reset_database.sh test and check the database to see if preqForProgram is added and column_id is added to event table. prgramEvent should no longer exist. 
Run tests again and they all should pass.

### CODE REVIEW

**Comment by BrianRamsay** [comment]
The whole reason we created ProgramEvent is that there are events that are in more than one program, meaning program_id in Event doesn't work.

You need to remove that part of these changes.

**Comment by BrianRamsay** [comment]
Training is not a separate program. Programs are specific CELTS initiatives. Events within a program can be classified as a training. I thought we said that isRequiredForProgram indicated a training?

If we want to make that clearer we can have other boolean flags. Like, we could do isTraining, or isPrerequisite, or isRequired. But creating new tables doesn't give us additional functionality that we need.

**Comment by bryantal** [comment]
@Sandesh-L @sreynit02 
Any update on this PR?

**Comment by sreynit02** [comment]
> @Sandesh-L @sreynit02
> Any update on this PR?

**Comment by sreynit02** [comment]
Sorry, I accidentally closed the PR by accident. But i've reopened it back

**Review by BrianRamsay — APPROVED** [review]
Looks good, pending our final conclusion on prerequisite and required events

**Pull request merged**
