### PR TITLE
Add reminder to update dietary restrictions on View Event Page

### LINKED ISSUE #811: If an event is marked with "Food is provided" add a reminder onto the sentence for volunteers to put in their dietary restrictions on their profiles.

### PR DESCRIPTION
**Pull request by sreynit02**
This PR resolves issue#811. 

Test: 
Create an event that will provide food. Then view event. 
You should see this: 
HHH

### CODE REVIEW

**Review by AndersonStettner — COMMENTED** [review]
One thing that might be nice is to make "dietary restrictions" redirect to the Dietary Restrictions accordion.

**Comment by AndersonStettner** [comment]
Brian's wording suggestion: "Inform us of your dietary restrictions on your User Profile." and make either the entire sentence a link or just make "User Profile" a link to the Dietary Restrictions accordion.

**Comment by AndersonStettner** [comment]
Any further work of this issue/pull request should be done on PR #819

**Comment by sreynit02** [comment]
> Brian's wording suggestion: "Inform us of your dietary restrictions on your User Profile." and make either the entire sentence a link or just make "User Profile" a link to the Dietary Restrictions accordion.

Made the sentence link to User Profile page. Cannot link to the Dietary Restrictions accordion just yet because it's not in development yet.

**Comment by BrianRamsay** [comment]
Merged with mega-branch

**Pull request closed without merging**
