### PR TITLE
Toggle fullscreen

### PR DESCRIPTION
**Pull request by MImran2002**
Hi Brain I have edited to button to make it look decent and good UI design and I have changed the Boolean parameter to make the toggle works

### CODE REVIEW

**Comment by MImran2002** [comment]
this is the issue  : https://github.com/BCStudentSoftwareDevTeam/celts/issues/1122

**Comment by Ndiayem14** [comment]
We reviewed this pull request, and it looks great. They did a good job, making it work as well as it should be. Good job guys.

**Comment by ali-ramazani** [comment]
We checked the website after the implemented fixes, and the issues were resolved. We also checked the code, and everything seemed fine. However, one small change we suggest is changing variable types from 'var' to 'let' to stick to modern JavaScript conventions and avoid potential errors.

**Review by BrianRamsay — APPROVED** [review]
Woohoo!

**Pull request merged**
